source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'TTKeyboardphobia_Example', :exclusive => true do
  pod "TTKeyboardphobia", :path => "../"
end

target 'TTKeyboardphobia_Tests', :exclusive => true do
  pod "TTKeyboardphobia", :path => "../"

  pod 'FBSnapshotTestCase'
  pod 'KIF'
end
